import React from 'react';

const Layout = () => {
  return (
    <main className='w-screen h-full flex flex-col p-5 gap-5 '>
      <header className='flex z-20 fixed top-0 justify-between items-center gap-5 h-fit py-5 w-[calc(100%-40px)] bg-white'>
        <div className='flex-1'>
          <input type="text" className='rounded-full w-full px-5 py-2 bg-slate-200' placeholder='Search' />
        </div>
        <div className='w-10 h-10 rounded-full bg-slate-200'></div>
      </header>
      <section className='w-[100%] relative top-16 rounded-xl'>
        <div className='float-left sticky top-20 sidebar w-[15%]  bg-slate-300 rounded-md flex flex-col items-start gap-1 p-2'>
          { Array.from( new Array( 10 ) ).map( () => (
            <div className='w-full h-10 transition-all hover:bg-slate-100 bg-slate-200 rounded-md flex pl-5 py-3 pr-3 items-center text-sm text-slate-400'>Content</div>
          ) ) }
        </div>
        <div className='float-left w-[calc(70%-40px)] relative left-[20px] p-2 bg-slate-300 rounded-md'>
          <div className='flex gap-5 flex-col pb-10'>
            <div className='flex-1 flex gap-5'>
              <div className='w-10 h-10 rounded-full bg-slate-200'></div>
              <div className='flex-1'>
                <input type="text" className='rounded-full w-full px-5 py-2 bg-slate-200' placeholder='Whats on your mind?' />
              </div>
            </div>
          </div>
          <div className='content'>

            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit placeat pariatur veritatis odit cupiditate accusantium! Voluptate facilis suscipit magnam repellendus eveniet nobis voluptatem necessitatibus enim impedit sed doloremque maxime asperiores aperiam saepe repudiandae ad ipsa a, accusamus numquam atque iure ratione. Numquam temporibus iure doloremque possimus, tempore, itaque quasi est praesentium earum, expedita culpa nostrum libero dicta! Fugit officiis ut doloremque mollitia perspiciatis neque, cupiditate vero pariatur quam non labore consequatur fugiat quod eum nobis esse? Error eaque omnis distinctio nobis quam. Eveniet ducimus cum reprehenderit, quam nam facere quisquam minima ad doloremque tenetur unde enim omnis soluta eius, optio natus fugiat. Ducimus voluptas consequuntur quis unde, animi, enim harum quo fuga iusto tenetur corrupti dolorem eaque autem nam non eligendi ab distinctio quae ullam natus iste aperiam illo cumque? Dolores voluptatem maxime provident ipsa voluptatum facilis tenetur, temporibus ullam! Sint nostrum est rerum libero quis quisquam nesciunt totam expedita quod mollitia nisi pariatur accusamus modi perspiciatis dolorum, sapiente praesentium perferendis quo laudantium cum aspernatur eius vitae? A rem alias quasi! Dicta, voluptate amet. Tenetur veritatis sit culpa possimus neque perspiciatis asperiores! Consequuntur eveniet a tempora quibusdam, ab labore vero alias ducimus accusamus cupiditate ut impedit molestiae aperiam dignissimos dicta!
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit placeat pariatur veritatis odit cupiditate accusantium! Voluptate facilis suscipit magnam repellendus eveniet nobis voluptatem necessitatibus enim impedit sed doloremque maxime asperiores aperiam saepe repudiandae ad ipsa a, accusamus numquam atque iure ratione. Numquam temporibus iure doloremque possimus, tempore, itaque quasi est praesentium earum, expedita culpa nostrum libero dicta! Fugit officiis ut doloremque mollitia perspiciatis neque, cupiditate vero pariatur quam non labore consequatur fugiat quod eum nobis esse? Error eaque omnis distinctio nobis quam. Eveniet ducimus cum reprehenderit, quam nam facere quisquam minima ad doloremque tenetur unde enim omnis soluta eius, optio natus fugiat. Ducimus voluptas consequuntur quis unde, animi, enim harum quo fuga iusto tenetur corrupti dolorem eaque autem nam non eligendi ab distinctio quae ullam natus iste aperiam illo cumque? Dolores voluptatem maxime provident ipsa voluptatum facilis tenetur, temporibus ullam! Sint nostrum est rerum libero quis quisquam nesciunt totam expedita quod mollitia nisi pariatur accusamus modi perspiciatis dolorum, sapiente praesentium perferendis quo laudantium cum aspernatur eius vitae? A rem alias quasi! Dicta, voluptate amet. Tenetur veritatis sit culpa possimus neque perspiciatis asperiores! Consequuntur eveniet a tempora quibusdam, ab labore vero alias ducimus accusamus cupiditate ut impedit molestiae aperiam dignissimos dicta!
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit placeat pariatur veritatis odit cupiditate accusantium! Voluptate facilis suscipit magnam repellendus eveniet nobis voluptatem necessitatibus enim impedit sed doloremque maxime asperiores aperiam saepe repudiandae ad ipsa a, accusamus numquam atque iure ratione. Numquam temporibus iure doloremque possimus, tempore, itaque quasi est praesentium earum, expedita culpa nostrum libero dicta! Fugit officiis ut doloremque mollitia perspiciatis neque, cupiditate vero pariatur quam non labore consequatur fugiat quod eum nobis esse? Error eaque omnis distinctio nobis quam. Eveniet ducimus cum reprehenderit, quam nam facere quisquam minima ad doloremque tenetur unde enim omnis soluta eius, optio natus fugiat. Ducimus voluptas consequuntur quis unde, animi, enim harum quo fuga iusto tenetur corrupti dolorem eaque autem nam non eligendi ab distinctio quae ullam natus iste aperiam illo cumque? Dolores voluptatem maxime provident ipsa voluptatum facilis tenetur, temporibus ullam! Sint nostrum est rerum libero quis quisquam nesciunt totam expedita quod mollitia nisi pariatur accusamus modi perspiciatis dolorum, sapiente praesentium perferendis quo laudantium cum aspernatur eius vitae? A rem alias quasi! Dicta, voluptate amet. Tenetur veritatis sit culpa possimus neque perspiciatis asperiores! Consequuntur eveniet a tempora quibusdam, ab labore vero alias ducimus accusamus cupiditate ut impedit molestiae aperiam dignissimos dicta!
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit placeat pariatur veritatis odit cupiditate accusantium! Voluptate facilis suscipit magnam repellendus eveniet nobis voluptatem necessitatibus enim impedit sed doloremque maxime asperiores aperiam saepe repudiandae ad ipsa a, accusamus numquam atque iure ratione. Numquam temporibus iure doloremque possimus, tempore, itaque quasi est praesentium earum, expedita culpa nostrum libero dicta! Fugit officiis ut doloremque mollitia perspiciatis neque, cupiditate vero pariatur quam non labore consequatur fugiat quod eum nobis esse? Error eaque omnis distinctio nobis quam. Eveniet ducimus cum reprehenderit, quam nam facere quisquam minima ad doloremque tenetur unde enim omnis soluta eius, optio natus fugiat. Ducimus voluptas consequuntur quis unde, animi, enim harum quo fuga iusto tenetur corrupti dolorem eaque autem nam non eligendi ab distinctio quae ullam natus iste aperiam illo cumque? Dolores voluptatem maxime provident ipsa voluptatum facilis tenetur, temporibus ullam! Sint nostrum est rerum libero quis quisquam nesciunt totam expedita quod mollitia nisi pariatur accusamus modi perspiciatis dolorum, sapiente praesentium perferendis quo laudantium cum aspernatur eius vitae? A rem alias quasi! Dicta, voluptate amet. Tenetur veritatis sit culpa possimus neque perspiciatis asperiores! Consequuntur eveniet a tempora quibusdam, ab labore vero alias ducimus accusamus cupiditate ut impedit molestiae aperiam dignissimos dicta!
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit placeat pariatur veritatis odit cupiditate accusantium! Voluptate facilis suscipit magnam repellendus eveniet nobis voluptatem necessitatibus enim impedit sed doloremque maxime asperiores aperiam saepe repudiandae ad ipsa a, accusamus numquam atque iure ratione. Numquam temporibus iure doloremque possimus, tempore, itaque quasi est praesentium earum, expedita culpa nostrum libero dicta! Fugit officiis ut doloremque mollitia perspiciatis neque, cupiditate vero pariatur quam non labore consequatur fugiat quod eum nobis esse? Error eaque omnis distinctio nobis quam. Eveniet ducimus cum reprehenderit, quam nam facere quisquam minima ad doloremque tenetur unde enim omnis soluta eius, optio natus fugiat. Ducimus voluptas consequuntur quis unde, animi, enim harum quo fuga iusto tenetur corrupti dolorem eaque autem nam non eligendi ab distinctio quae ullam natus iste aperiam illo cumque? Dolores voluptatem maxime provident ipsa voluptatum facilis tenetur, temporibus ullam! Sint nostrum est rerum libero quis quisquam nesciunt totam expedita quod mollitia nisi pariatur accusamus modi perspiciatis dolorum, sapiente praesentium perferendis quo laudantium cum aspernatur eius vitae? A rem alias quasi! Dicta, voluptate amet. Tenetur veritatis sit culpa possimus neque perspiciatis asperiores! Consequuntur eveniet a tempora quibusdam, ab labore vero alias ducimus accusamus cupiditate ut impedit molestiae aperiam dignissimos dicta!
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit placeat pariatur veritatis odit cupiditate accusantium! Voluptate facilis suscipit magnam repellendus eveniet nobis voluptatem necessitatibus enim impedit sed doloremque maxime asperiores aperiam saepe repudiandae ad ipsa a, accusamus numquam atque iure ratione. Numquam temporibus iure doloremque possimus, tempore, itaque quasi est praesentium earum, expedita culpa nostrum libero dicta! Fugit officiis ut doloremque mollitia perspiciatis neque, cupiditate vero pariatur quam non labore consequatur fugiat quod eum nobis esse? Error eaque omnis distinctio nobis quam. Eveniet ducimus cum reprehenderit, quam nam facere quisquam minima ad doloremque tenetur unde enim omnis soluta eius, optio natus fugiat. Ducimus voluptas consequuntur quis unde, animi, enim harum quo fuga iusto tenetur corrupti dolorem eaque autem nam non eligendi ab distinctio quae ullam natus iste aperiam illo cumque? Dolores voluptatem maxime provident ipsa voluptatum facilis tenetur, temporibus ullam! Sint nostrum est rerum libero quis quisquam nesciunt totam expedita quod mollitia nisi pariatur accusamus modi perspiciatis dolorum, sapiente praesentium perferendis quo laudantium cum aspernatur eius vitae? A rem alias quasi! Dicta, voluptate amet. Tenetur veritatis sit culpa possimus neque perspiciatis asperiores! Consequuntur eveniet a tempora quibusdam, ab labore vero alias ducimus accusamus cupiditate ut impedit molestiae aperiam dignissimos dicta!
            </p>
          </div>
        </div>
        <div className='chat-section float-right sticky h-[calc(100vh-92px)] top-20 right-0 w-[15%] bg-slate-200 rounded-md flex flex-col gap-5 p-2'>
          <div className='friend-list w-full h-full top-0 bg-slate-300 rounded-md flex flex-col items-start gap-2 p-2 overflow-y-auto'>
            { Array.from( new Array( 10 ) ).map( () => (
              <div className='w-full h-8 transition-all hover:bg-slate-100 bg-slate-200 rounded flex pl-5 py-3 pr-3 items-center text-sm text-slate-400'>Friend</div>
            ) ) }
          </div>
          <div className="chat z-20 w-[33%] h-10 absolute bottom-0 right-[100%] rounded-md bg-slate-600"></div>
        </div>
      </section>
    </main>
  );
};

export default Layout;